import OpenAI, { AzureOpenAI } from "openai";
import { db } from "../db";
import { customAgents, organizations, type CustomAgent, type FridayAgentConfig } from "@shared/schema";
import { and, eq, isNull, lte, sql } from "drizzle-orm";
import { withAiCredits, AiCreditsLimitError, resolveSystemUserId } from "./aiCredits";
import { decryptApiKey } from "../routes/helpers";
import { sendEmail } from "./email";
import { logAgentRun } from "../storage/customAgentStorage";
import { gatherOrganizationContext, type CustomAgentRuntimeConfig } from "./jarvisService";
import { calculateNextWeeklyRun } from "./projectAgentService";

function defaultClient(): { client: OpenAI; deployment: string; isAzure: boolean } {
  if (process.env.AZURE_OPENAI_API_KEY && process.env.AZURE_OPENAI_ENDPOINT) {
    return {
      client: new AzureOpenAI({
        apiKey: process.env.AZURE_OPENAI_API_KEY,
        endpoint: process.env.AZURE_OPENAI_ENDPOINT,
        apiVersion: process.env.AZURE_OPENAI_API_VERSION || "2024-12-01-preview",
      }),
      deployment: process.env.AZURE_OPENAI_DEPLOYMENT || "gpt-4.1",
      isAzure: true,
    };
  }
  return {
    client: new OpenAI({
      apiKey: process.env.OPENAI_API_KEY || process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
      baseURL: process.env.OPENAI_API_KEY ? undefined : process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
    }),
    deployment: "gpt-4o-mini",
    isAzure: false,
  };
}

async function getOrgClient(orgId: number) {
  try {
    const [org] = await db.select({ fridayAgentConfig: organizations.fridayAgentConfig })
      .from(organizations).where(eq(organizations.id, orgId));
    const cfg = org?.fridayAgentConfig as FridayAgentConfig | null;
    // When the org has selected Anthropic, custom agents fall back to the
    // system default OpenAI/Azure client (this service is OpenAI-only for now).
    if (cfg?.provider !== "anthropic" && cfg?.useOrgAzure && cfg.azureEndpoint && cfg.azureApiKey) {
      const apiKey = decryptApiKey(cfg.azureApiKey);
      return {
        client: new AzureOpenAI({
          apiKey,
          endpoint: cfg.azureEndpoint,
          apiVersion: cfg.azureApiVersion || "2024-12-01-preview",
        }),
        deployment: cfg.azureDeployment || "gpt-4.1",
        isAzure: true,
      };
    }
  } catch (e) {
    console.error(`[customAgent] Failed to load org ${orgId} Azure cfg:`, e);
  }
  return defaultClient();
}

function buildScopeSummary(ctx: any, scope: CustomAgentRuntimeConfig["dataScope"]): string {
  const projects = (ctx.projects ?? []).slice(0, 30).map((p: any) => `- ${p.name} (id ${p.id}, status ${p.status || "n/a"}, health ${p.health || "n/a"})`).join("\n");
  const tasks = (ctx.tasks ?? []).slice(0, 60).map((t: any) => `- ${t.name} [${t.status || "n/a"}] (project ${t.projectId})`).join("\n");
  const issues = (ctx.issues ?? []).slice(0, 30).map((i: any) => `- [${i.itemType || "issue"} | ${i.priority || "med"}] ${i.title}`).join("\n");
  return `Data scope: ${scope.type}\nProjects (${ctx.projects?.length || 0}):\n${projects || "none"}\n\nTasks (top):\n${tasks || "none"}\n\nIssues/Risks (top):\n${issues || "none"}`;
}

function htmlWrap(title: string, body: string): string {
  return `<!doctype html><html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:720px;margin:0 auto;padding:24px;color:#0f172a">
<h2 style="margin:0 0 16px 0;color:#0f172a">${title}</h2>
<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:20px;line-height:1.6">${body}</div>
<p style="margin-top:24px;color:#64748b;font-size:12px">Generated by FridayReport.AI custom agent</p>
</body></html>`;
}

export async function runScheduledAgent(
  agent: CustomAgent,
  triggeredBy: string | null = null,
): Promise<{ status: "success" | "error" | "skipped"; message?: string }> {
  if (agent.type !== "scheduled") return { status: "skipped", message: "Not a scheduled agent" };
  const recipients = (agent.recipientEmails ?? []).filter(Boolean);
  if (recipients.length === 0) {
    await logAgentRun({ agentId: agent.id, status: "skipped", subject: agent.name, errorMessage: "No recipients configured", triggeredBy });
    return { status: "skipped", message: "No recipients" };
  }
  // Email delivery is an explicit, separately-toggled permission. Even if
  // recipients are configured, a scheduled agent must hold the `send_email`
  // action to actually deliver the report — this prevents accidental
  // exfiltration of org/portfolio AI summaries to outside addresses.
  const allowEmail = (agent.allowedTools ?? []).includes("send_email");
  if (!allowEmail) {
    await logAgentRun({
      agentId: agent.id, status: "skipped", subject: agent.name,
      recipientEmails: recipients,
      errorMessage: "Email delivery is not enabled for this agent (toggle the 'send_email' action).",
      triggeredBy,
    });
    return { status: "skipped", message: "send_email not enabled" };
  }

  const chargeUserId = agent.createdBy || (await resolveSystemUserId(agent.organizationId));
  if (!chargeUserId) {
    await logAgentRun({ agentId: agent.id, status: "skipped", subject: agent.name, errorMessage: "No user to bill", triggeredBy });
    return { status: "skipped", message: "No billable user" };
  }

  try {
    let ctx = await gatherOrganizationContext(agent.organizationId);
    const scope = agent.dataScope as CustomAgentRuntimeConfig["dataScope"];
    if (scope.type !== "org") {
      let allowed: Set<number>;
      if (scope.type === "projects") allowed = new Set(scope.projectIds ?? []);
      else {
        const ps = new Set(scope.portfolioIds ?? []);
        allowed = new Set(ctx.projects.filter((p: any) => p.portfolioId && ps.has(p.portfolioId)).map((p: any) => p.id));
      }
      ctx = {
        ...ctx,
        projects: ctx.projects.filter((p: any) => allowed.has(p.id)),
        tasks: ctx.tasks.filter((t: any) => allowed.has(t.projectId)),
        issues: ctx.issues.filter((i: any) => allowed.has(i.projectId)),
      };
    }

    const { client, deployment, isAzure } = await getOrgClient(agent.organizationId);
    const summary = buildScopeSummary(ctx, scope);

    const completion = await withAiCredits(
      { userId: chargeUserId, orgId: agent.organizationId, action: "custom_scheduled_agent", entityId: agent.id },
      () => client.chat.completions.create({
        model: isAzure ? deployment : (agent.model || "gpt-4o-mini"),
        messages: [
          { role: "system", content: `${agent.systemPrompt}\n\nYou are generating a scheduled report. Output clean HTML (no <html>/<body>), suitable for an email body. Use <h3>, <ul>/<li>, and short paragraphs. Be concrete; cite project/task names.` },
          { role: "user", content: `Generate the report now. Use only the data below.\n\n${summary}` },
        ],
        max_tokens: 1800,
        temperature: 0.3,
      }),
    );

    const reportHtml = completion.choices[0]?.message?.content?.trim() || "<p>No content generated.</p>";
    const subject = (agent.emailSubject?.trim() || `${agent.name} — scheduled report`).slice(0, 200);
    const html = htmlWrap(agent.name, reportHtml);

    let anySent = false;
    const emailErrors: string[] = [];
    for (const to of recipients) {
      try {
        const ok = await sendEmail({ to, subject, text: agent.name, html });
        if (ok) anySent = true;
        else emailErrors.push(`${to}: sendEmail returned false`);
      } catch (e: any) {
        emailErrors.push(`${to}: ${e?.message ?? "error"}`);
        console.error(`[customAgent] sendEmail failed for ${to}:`, e);
      }
    }

    if (!anySent) {
      await logAgentRun({
        agentId: agent.id, status: "error", subject, recipientEmails: recipients,
        emailPreview: reportHtml.substring(0, 2000),
        errorMessage: `Email delivery failed: ${emailErrors.join("; ").slice(0, 800)}`,
        triggeredBy,
      });
      return { status: "error", message: "email delivery failed" };
    }

    await logAgentRun({
      agentId: agent.id, status: "success", subject, recipientEmails: recipients,
      emailPreview: reportHtml.substring(0, 2000),
      errorMessage: emailErrors.length > 0 ? `Partial: ${emailErrors.join("; ").slice(0, 600)}` : null,
      triggeredBy,
    });
    return { status: "success" };
  } catch (err: any) {
    if (err instanceof AiCreditsLimitError) {
      await logAgentRun({ agentId: agent.id, status: "skipped", subject: agent.name, errorMessage: "AI credit limit reached", triggeredBy });
      return { status: "skipped", message: "credit limit" };
    }
    await logAgentRun({ agentId: agent.id, status: "error", subject: agent.name, errorMessage: err?.message?.slice(0, 1000) || "Unknown error", triggeredBy });
    return { status: "error", message: err?.message };
  }
}

export async function checkAndRunDueCustomScheduledAgents(): Promise<number> {
  const now = new Date();
  const due = await db.select().from(customAgents).where(
    and(
      eq(customAgents.type, "scheduled"),
      eq(customAgents.enabled, true),
      isNull(customAgents.archivedAt),
      sql`${customAgents.nextRun} IS NOT NULL AND ${customAgents.nextRun} <= ${now}`,
    )
  );
  let count = 0;
  for (const a of due) {
    try {
      const r = await runScheduledAgent(a, null);
      if (r.status === "success") count++;
    } catch (e) {
      console.error(`[customAgent] run failed for ${a.id}:`, e);
    }
    const next = (a.scheduleDay != null && a.scheduleTime)
      ? calculateNextWeeklyRun(a.scheduleDay, a.scheduleTime, a.timezone || "America/New_York")
      : null;
    await db.update(customAgents).set({ lastRun: now, nextRun: next, updatedAt: new Date() }).where(eq(customAgents.id, a.id));
  }
  return count;
}

export function computeNextRun(scheduleDay: number | null | undefined, scheduleTime: string | null | undefined, tz: string | null | undefined): Date | null {
  if (scheduleDay == null || !scheduleTime) return null;
  return calculateNextWeeklyRun(scheduleDay, scheduleTime, tz || "America/New_York");
}
